import { Inter } from 'next/font/google'
import Footer from './componets/parts/Footer'
import Sidebar from './componets/Sidebar'
import './globals.css'
import MobileNavbar from './componets/MobileNavbar'
import ScrollUpButton from './utlis/ScrollUpButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
          <div className='flex min-h-screen relative'>
            <div className='md:w-2/6 lg:w-1/6 bg-violet-700 hidden md:block'>  
              <Sidebar />
            </div>
            <div className='w-full content md:w-4/6 lg:w-5/6 bg-slate-200'>
              {/* Mobile Navbar  */}
              <MobileNavbar />
              {children}
              <ScrollUpButton />
              <Footer />
            </div>
          </div>
      </body>
    </html>
  )
}
